# This notebook will be used for testing each section

In [20]:
from src.main import *
from src.treegen import *
from src.optimalsplit import *
from src.crosseval import *
from src.prune import *
import importlib
from src.evaluation import *


In [21]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [22]:
treeNode = tree_gen()
# Steps to visualise:
data = treeNode.sample_data
root, depth = treeNode.generateTree(data, 0)
#root, depth = treeNode.generate_decision_tree(treeNode.sample_data, 0)
#fig, ax = plt.subplots(figsize=(18, 10))
#gap = 1.0/depth
#treeNode.visualize_tree(root, 0.0, 1.0, 0.0, 1.0)
#fig.subplots_adjust(top=0.83)
#plt.show()

tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished


In [23]:
bottom =np.where(data[:, 6] > -83)
print(bottom)
print(data[bottom])

(array([ 0,  3,  4,  6,  7,  9, 14, 16, 18, 20, 22, 23, 24, 25, 26, 28, 29,
       30, 31, 33, 34, 36, 37, 40, 41], dtype=int64),)
[[-35. -56. -57. -34. -60. -73. -80.   2.]
 [-19. -63. -66. -20. -79. -73. -72.   2.]
 [-39. -56. -58. -37. -64. -76. -72.   2.]
 [-52. -52. -52. -49. -62. -80. -80.   3.]
 [-40. -50. -49. -51. -65. -75. -80.   2.]
 [-36. -50. -58. -41. -74. -74. -69.   2.]
 [-38. -54. -52. -36. -63. -65. -70.   2.]
 [-38. -56. -48. -39. -63. -70. -73.   2.]
 [-65. -54. -57. -66. -70. -82. -80.   1.]
 [-37. -59. -57. -36. -64. -66. -70.   2.]
 [-37. -58. -56. -38. -63. -75. -74.   2.]
 [-58. -54. -52. -61. -74. -75. -82.   1.]
 [-44. -59. -63. -42. -72. -79. -80.   2.]
 [-37. -56. -55. -45. -64. -61. -69.   2.]
 [-57. -56. -47. -58. -44. -88. -82.   4.]
 [-64. -52. -63. -62. -71. -84. -79.   1.]
 [-40. -56. -56. -38. -66. -77. -74.   2.]
 [-59. -57. -60. -58. -67. -80. -79.   1.]
 [-58. -56. -61. -66. -75. -84. -78.   1.]
 [-46. -56. -54. -49. -63. -81. -82.   3.]
 [-38. -5

In [24]:
root.printTree()

            -> x1
        -> x4 <= -66.0
            -> x4
    -> x3 <= -58.0
                -> x3
            -> x1 <= -60.0
                    -> x4
                -> x0 <= -57.0
                    -> x3
        -> x5 <= -83.0
                -> x3
            -> x2 <= -53.0
                    -> x3
                -> x0 <= -52.0
                    -> x2
-> x3 <= -46.0
    -> x2
up means true, down means false


In [25]:
eval = Evaluation(np.loadtxt("test/clean_dataset.txt", dtype=float))

[[-49. -59. -57. ... -85. -83.   3.]
 [-52. -57. -53. ... -80. -83.   3.]
 [-38. -52. -56. ... -71. -75.   2.]
 ...
 [-38. -52. -54. ... -73. -77.   2.]
 [-37. -61. -55. ... -70. -67.   2.]
 [-50. -55. -59. ... -75. -78.   2.]]
TEST SET: 
[[-63. -56. -52. ... -82. -92.   4.]
 [-60. -60. -46. ... -81. -83.   4.]
 [-48. -56. -54. ... -78. -82.   2.]
 ...
 [-38. -52. -54. ... -73. -77.   2.]
 [-37. -61. -55. ... -70. -67.   2.]
 [-50. -55. -59. ... -75. -78.   2.]]
TRAING SET: 
1800
