# This notebook will be used for testing each section

In [66]:
from src.main import *
from src.treegen import *
from src.optimalsplit import *
from src.crosseval import *
from src.prune import *
import importlib


In [67]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [96]:
treeNode = tree_gen()
# Steps to visualise:
data = treeNode.sample_data
root, depth = treeNode.generateTree(data, 0)
#root, depth = treeNode.generate_decision_tree(treeNode.sample_data, 0)
#fig, ax = plt.subplots(figsize=(18, 10))
#gap = 1.0/depth
#treeNode.visualize_tree(root, 0.0, 1.0, 0.0, 1.0)
#fig.subplots_adjust(top=0.83)
#plt.show()

tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished


In [75]:
bottom =np.where(data[:, 6] > -83)
print(bottom)
print(data[bottom])

(array([0, 3, 4], dtype=int64),)
[[-35. -56. -57. -34. -60. -73. -80.   2.]
 [-19. -63. -66. -20. -79. -73. -72.   2.]
 [-39. -56. -58. -37. -64. -76. -72.   2.]]


In [101]:
root.printTree()

            -> x1
        -> x4 <= -66.0
            -> x4
    -> x3 <= -58.0
                -> x3
            -> x1 <= -60.0
                    -> x4
                -> x0 <= -57.0
                    -> x3
        -> x5 <= -83.0
                -> x3
            -> x2 <= -53.0
                    -> x3
                -> x0 <= -52.0
                    -> x2
-> x3 <= -46.0
    -> x2
up means true, down means false
