# This notebook will be used for testing each section

In [66]:
from src.main import *
from src.treegen import *
from src.optimalsplit import *
from src.crosseval import *
from src.prune import *
import importlib


In [67]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [102]:
treeNode = tree_gen()
# Steps to visualise:
data = treeNode.sample_data
root, depth = treeNode.generateTree(data, 0)
#root, depth = treeNode.generate_decision_tree(treeNode.sample_data, 0)
#fig, ax = plt.subplots(figsize=(18, 10))
#gap = 1.0/depth
#treeNode.visualize_tree(root, 0.0, 1.0, 0.0, 1.0)
#fig.subplots_adjust(top=0.83)
#plt.show()

tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree finished
tree f

In [75]:
bottom =np.where(data[:, 6] > -83)
print(bottom)
print(data[bottom])

(array([0, 3, 4], dtype=int64),)
[[-35. -56. -57. -34. -60. -73. -80.   2.]
 [-19. -63. -66. -20. -79. -73. -72.   2.]
 [-39. -56. -58. -37. -64. -76. -72.   2.]]


In [103]:
root.printTree()

                        -> x1
                    -> x4 <= -72.0
                            -> x1
                        -> x6 <= -89.0
                                    -> x1
                                -> x5 <= -85.0
                                                -> x1
                                            -> x0 <= -60.0
                                                    -> x1
                                                -> x0 <= -58.0
                                                    -> x3
                                        -> x6 <= -86.0
                                            -> x1
                                    -> x1 <= -57.0
                                            -> x1
                                        -> x2 <= -61.0
                                                -> x1
                                            -> x0 <= -60.0
                                                -> x4
                            -> x5 <= -82.0
          